{{- if not .Values.core.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secrets" (include "backend.fullname" .) }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.core.token }}
  token: {{ . | quote }}
  {{- end }}
  {{- with .Values.core.registrationToken }}
  registrationToken: {{ . | quote }}
  {{- end }}
  {{- with .Values.core.sharedKey }}
  sharedKey: {{ . | quote }}
  {{- end }}
  {{- if and .Values.provider.apiKey (not .Values.provider.existingSecret) }}
  apiKey: {{ .Values.provider.apiKey | quote }}
  {{- end }}
{{- end }}
